### ISSUE TITLE
WebIO dependency

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGizmos/JSExpr.jl#2]
Nice idea to have this as a separate package (and it e.g. avoids me having to duplicate code [here](https://github.com/FluxML/FluxJS.jl/blob/bb16a8515c40068e1a153e016ff2c5732565aabb/src/dump.jl) for example), but I wonder if we can avoid special-casing WebIO too much, to make things more general.

In general, packages that want custom semantics should *probably* provide their own `@js` and do custom lowering; I don't think this is a huge deal for WebIO as (1) it's important and (2) `x[]` isn't valid JS anyway, so it's not likely to bite non-WebIO users.

However, maybe it'd make sense for JSExpr to provide custom handlers for different syntax (eg. `JSExpr.handle((io, Expr) -> Bool)`. This might be a nice refactoring anyway, and would allow us to reverse the WebIO/JSExpr dependency.

**Comment by shashi** [comment]
Yeah, WebIO dependency here was sort of a stop-gap till I figure out these issues, we should remove it.

**Comment by twavv** [comment]
Closed by #31 .
