### ISSUE TITLE
Compat for JSON

### ISSUE THREAD

**Issue by KristofferC** [JuliaGizmos/JSExpr.jl#35]
Currently, the 1.0+ releases are yanked in the registry. The pre 1.0 version (0.5.1) claims to only be compatible with JSON 0.18 which is a quite old JSON release. It would be great if a new (0.5.2) release could be made that has compat with the newer JSON (up to 0.21).

**Comment by fredrikekre** [comment]
See https://github.com/JuliaGizmos/JSExpr.jl/commit/8aecd2cd6f0fd415e61cce1ba395f3d11b234b07#commitcomment-37777787 which is waiting for https://github.com/JuliaRegistries/Registrator.jl/pull/255

**Comment by tlienart** [comment]
Now that the above has been merged & released (https://github.com/JuliaRegistries/General/pull/11423) should this be closed?
