### ISSUE TITLE
Add Math. to known math function calls

### ISSUE THREAD

**Issue by tlienart** [JuliaGizmos/JSExpr.jl#36]
```julia
julia> @js (a,b) -> a*sin(b)
JSString("(function (a,b){return (a*sin(b))})")
```

it could be nice to map the standard mathematical functions like `sin, cos, tan, sqrt, ...` to their JS counterpart like `Math.sin, Math.cos, Math.tan, Math.sqrt`; the [list of js math functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math) seems to suggest this is fairly straightforward (names are mostly identical).

Another nice step would be to interpolate symbols like `π` or `ℯ`.

PS: I'm happy to try to open a PR but I'd need some guidance as to what's the likely good way to go about this

**Comment by twavv** [comment]
I'm opposed to this change, though I'm willing to consider it.

(IMO) I think it should be very clear that the code you are writing is **not** Julia - it is JS, and I'm opposed to anything that lulls the user into thinking that they're writing Julia. JS is very different from Julia and sometimes has very different semantics.

If someone wants to simulate this themself, they can just do
```julia
const setup_function @js function()
  for s in ["sin", "cos", "tan", "sqrt"]
    # .bind might not be necessary for math functions, but better safe than sorry
    window[s] = Math[s].bind(Math)
  end
end
```

**Comment by tlienart** [comment]
fair enough, I might do this in a secondary package, thanks for the tip! feel free to close this issue

**Comment by twavv** [comment]
In the v1 of JSExpr (which is unreleased because I've yet to go update WebIO to be compatible), there's functionality that makes it really easy to extend existing JSExpr functionality (the only downside is that it's global, so might adversely impact unrelated modules if they happen to use identifiers named `sin`, `cos`, etc.)
