### ISSUE TITLE
Missing 1.0.x ? can't install 1.0.x

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaGizmos/JSExpr.jl#38]
According to https://github.com/JuliaRegistries/General/blob/master/J/JSExpr/Versions.toml or https://github.com/JuliaGizmos/JSExpr.jl/blob/master/Project.toml#L4, it looks like this Julia package JSExpr.jl released with 1.0.x (x=0 or 1). However I can't install on my MacBook. 🤔 

```julia
pkg> add JSExpr@1.0.0
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JSExpr [97c1335a]:
 JSExpr [97c1335a] log:
 ├─possible versions are: [0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.2] or uninstalled
 └─restricted to versions 1.0.0 by an explicit requirement — no versions left
```

**Comment by twavv** [comment]
It was un-released because it caused issues in WebIO and other downstream packages, unfortunately. It's currently effectively not released.
