### ISSUE TITLE
Way to do more complicated functions

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/JSExpr.jl#5]
currently, the following doesn't work:

```julia
@js :(
      e ->
        console.log("woof")
        $cur_observer[] = e.keyCode
        console.log("bark")
    ))
```

-----

can you think of why this would fail to compile?

**Comment by djsegal** [comment]
@shashi sorry for badgering you again :( 

// this just seemed up your alley

------

**edit:** current workaround is making a global javascript function and calling it through @js

**Comment by shashi** [comment]
```
@js function (e)
        console.log("woof")
        $cur_observer[] = e.keyCode
        console.log("bark")
end
```

should work.

no worries, good to catch problems now.

**Comment by shashi** [comment]
In general, anything too complex can be

1. written in a `js""` string macro, and then interpolated into a `@js` expression (or the other way around)
2. added to the translator by opening issues and PRs :upside_down_face:

**Comment by djsegal** [comment]
two questions related to that.

1) how exactly would you go from `js"""` to `@js` notation with something like `$cur_observer` present
2) can you do conditionals within `@js`?

-----

I'm getting an error from:

```julia
@js function (cur_event)
  if (15 < 18) {
    greeting = "Good day";
  }

  $cur_observer[] = cur_event.keyCode
  console.log("bark")
end
```

```julia
ParseError("space before \"{\" not allowed in \"<(15,18) {\"")
```

**Comment by djsegal** [comment]
The problem with the if statement above is that it uses curly braces.

In JSExpr, you should use:

```
if blah
   ...
end
```

**Comment by shashi** [comment]
> how exactly would you go from js""" to @js notation with something like $cur_observer present

I don't think I understand the question. Note that you can interpolate $cur_observer into `js""" """` as well once you've loaded JSExpr.
